### ISSUE TITLE
AssertionError in File "evaluate.py", line 170, in main

### ISSUE THREAD

**Issue by arch-raven** [zhaoxlpku/KnowledGPT#6]
Terminal command run: `python evaluate.py --eval_batch_size 2 --gpu_list 1 --exp_name test`

```python
GPU_RATIO=0.85
KNOWLEDGE_TRUNCATE=64
LENGTH_PENALTY=1.0
LOAD_DIS=True
LOAD_GEN=True
LOG=wizard_of_wikipedia/log
LSTM_HIDDEN=256
LSTM_LAYER=1
MAX_LENGTH=30
MIN_LENGTH=15
N_SENT=1
NO_CUDA=False
NO_REPEAT_NGRAM_SIZE=0
REPETITION_PENALTY=1.0
SEED=42
SEGMENT=True
TEST_SEEN_FILE=wizard_of_wikipedia/data/test_seen.jsonl
TEST_UNSEEN_FILE=wizard_of_wikipedia/data/test_unseen.jsonl
TEXT_TRUNCATE=64

Writing to wizard_of_wikipedia/log/test

Create training dataset begain... | 2021-05-23 13:58:07 
Create training dataset end... | 2021-05-23 13:58:07 
Traceback (most recent call last):
  File "evaluate.py", line 312, in <module>
    main(args)
  File "evaluate.py", line 170, in main
    gen_batcher = GenBatcher(args.knowledge_truncate, args.text_truncate, args.gpt2_truncate, args.gpt2_config, args.cuda)
  File "/home1/deeksha/aditya/KnowledGPT/utils.py", line 103, in __init__
    self.tokenizer = GPT2Tokenizer.from_pretrained(gpt2_config)
  File "/home1/deeksha/anaconda3/envs/aditya/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 394, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home1/deeksha/anaconda3/envs/aditya/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 545, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home1/deeksha/anaconda3/envs/aditya/lib/python3.6/site-packages/transformers/tokenization_gpt2.py", line 149, in __init__
    super().__init__(bos_token=bos_token, eos_token=eos_token, unk_token=unk_token, **kwargs)
  File "/home1/deeksha/anaconda3/envs/aditya/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 338, in __init__
    assert isinstance(value, str)
AssertionError
```

Line 337 block in .../lib/python3.6/site-packages/transformers/tokenization_utils.py
```python
for key, value in kwargs.items():
      if key in self.SPECIAL_TOKENS_ATTRIBUTES:
          # import pdb; pdb.set_trace()
          if key == "additional_special_tokens":
              assert isinstance(value, (list, tuple)) and all(isinstance(t, str) for t in value)
          else:
              assert isinstance(value, str)
          setattr(self, key, value)
```

**Comment by arch-raven** [comment]
I am not sure what the error was, but doing the same thing on a different device worked.
